name: Kwiki-ReferrerLog
version: 0.05
abstract: Log Referrers to your Kwiki
author: Benjamin Reitzammer <cpan@nur-eine-i.de>
license: perl
distribution_type: module
requires:
  perl: 5.6.1
  Kwiki: 0.30
  Storable: POSIX
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.35
